= https://isaqb.org[iSAQB] Advanced Level Curriculum DSL – Domain-Specific Languages


:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status 
image:https://github.com/isaqb-org/curriculum-dsl/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-dsl/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-dsl.svg["Contributors",link="https://github.com/isaqb-org/curriculum-dsl/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-dsl.svg["Issues",link="https://github.com/isaqb-org/curriculum-dsl/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-dsl.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-dsl/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the iSAQB Advanced Level *curriculum* DSL – Domain-Specific languages

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to build this curriculum

. Clone the repository—including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-dsl.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-dsl.git --recursive
----
--
. Build the project with http://www.gradle.com[gradle] (you need a locally installed JDK, up to version 15) via `./gradlew`.
. Once "BUILD SUCCESSFUL" is shown, you can review the build result under `./build/index.html`


You build the output documents with gradle.
That will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration.

In case you want to change that, adjust the following part of `build.gradle`:

[source,groovy]
----
task buildDocs {
  group 'Documentation'
  description 'Grouping task for generating all languages in several formats'
  dependsOn "renderDE", "renderEN"
}
----

In the task "renderDE", certain attributes (aka variables) are defined that configure the corresponding output.

== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by Michael Sperber and Lars Hupel.
It was forked from https://github.com/isaqb-org/curriculum-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
