=== {learning-goals}

// tag::DE[]
// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Basics of semantics

* Understand the difference between compilers and interpreters.
* Understand the independence of a language's semantics and its (multiple) implementations.
* Understand the difference between a specification and an implementation.

[[LG-3-2]]
==== LG 3-2: Expressiveness

* Know various computation models, such as Lambda Calculus, Turing machines, rewriting systems, and finite state machines.
* Understand the principle of least power, in which the least expressive computation model should be chosen to represent the business domain; and when to deviate from the principle.
* Understand the connection between expressiveness and compilation (or interpretation).
* Can isolate static and dynamic parts of computation.

[[LG-3-3]]
==== LG 3-3: Design of semantics

* Know various types of semantics, such as denotational and operational semantics, as well as big- and small-step semantics.
* Understand the connection between the semantics of the DSL and the semantics of the target languages (compilation) and/or host languages (interpretation).
* Know how to define a semi-formal semantics of a DSL using a prose representation.
// end::EN[]
