// header file for curriculum section "References"
// (c) iSAQB e.V. (https://isaqb.org)
// ===============================================

[bibliography]
== {references}

// tag::DE[]
Dieser Abschnitt enthält Quellenangaben, die ganz oder teilweise im Curriculum referenziert werden.
// end::DE[]

// tag::EN[]
This section contains references that are cited in the curriculum.
// end::EN[]

**A**

- [[[aho,Aho et al. 2006]]] Aho, Alfred, Lam, Monica, Sethi, Ravi,
  Ullman, Jeffrey: Compilers: Principles, Techniques, and Tools.
  Addison Wesley, 2006.

**B**

- [[[baader,Baader and Nipkow 1998]]] Baader, Franz, Nipkow, Tobias:
  Term Rewriting and All That. Cambridge University Press, 1998.

- [[[bettini,Bettini 2016]]] Bettini, Lorenzo:
  Implementing Domain-Specific Languages with Xtext and Xtend -
  Second Edition. Packt, 2016.

**C**

- [[[culpepper,Culpepper et al. 2019]]] Culpepper, Ryan,
  Felleisen, Matthias, Flatt, Matthew, Krishnamurthi, Shriram: From
  Macros to DSLs: The Evolution of Racket. Summit on Advances in
  Programming Languages, 2019.
  https://cs.brown.edu/~sk/Publications/Papers/Published/cffk-macros-to-dsls/

**E**

- [[[elliott,Elliott and Hudak 1997]]] Elliott, Conal, Hudak, Paul:
  Functional reactive animation.  In ACM SIGPLAN International
  Conference on Functional Programming (ICFP '97). pages 263-273. ACM,
  Amsterdam.

- [[[evans,Evans 2003]]] Evans, Eric J.:
  Domain-Driven Design: Tackling Complexity in the Heart of Software.
  Addison-Wesley, 2003.

- [[[erdweg,Erdweg at el.]]] Sebastian, Erdweg et al.: Evaluating and
  comparing language workbenches: Existing results and benchmarks for
  the future.  In Computer Languages, Systems & Structures, 44:24–47, 2015.

**F**

- [[[felleisen,Felleisen et al. 2009]]] Felleisen, Matthias, Finder,
  Robert Bruce, Flatt, Matthew: Semantics Engineering with PLT Redex .
  MIT Press, 2009.

**H**

- [[[humer,Humer et al. 2014]]] Humer, Christian, et al.: A
  Domain-Specific Language for Building Self-Optimizing AST
  Interpreters. In Proceedings of the International Conference on
  Generative Programming: Concepts and Experiences (GPCE'14), 2014.

**L**

- [[[leermakers,Leermakers 1993]]] Leermakers, René: The Functional Treatment of
  Parsing. Springer Science, 1993.

**N**

- [[[nipkow,Nipkow and Klein 2014]]] Nipkow, Tobias, Klein, Gerwin:
  Concrete Semantics. Springer, 2014.

- [[[nystrom,Nytrom 2021]]] Nystrom, Robert: Crafting Interpreters.
  Genever Benning, 2021.

**P**

- [[[pierce,Pierce 2002]]] Pierce, Benjamin C.: Types and Programming Languages.
  MIT Press, 2002.

- [[[eber,Peyton Jones and Eber 2003]]] Peyton Jones, Simon, Eber,
  Jean-Marc: How to write a financial contract. Chapter in “The Fun
  of Programming”, ed. Gibbons and de Moor, Palgrave Macmillan 2003.

**S**

- [[[steinberg,Steinberg et al. 2008]]] Steinberg, Dave, Budinsky, Frank,
  Paternostro, Marcelo, Merks, Ed: EMF: Eclipse Modeling Framework,
  2nd edition. Addison-Wesley, 2008.

**V**

- [[[voelter13,Völter 2013]]] Völter, Markus:
  DSL Engineering: Designing, Implementing and Using Domain-Specific Languages.
  2013

- [[[voelter,Völter et al. 2014]]] Völter, Markus, Siegmun, Janet,
  Berge,  Thorsten, Kolb, Bernd: Towards user-friendly
  projectional editors. In International Conference on Software
  Language Engineering 2014. 41-61. Springer.

**W**

- [[[wilhelm,Wilhelm et al. 2021]]]  Wilhelm, Reinhard, Seidl, Helmut,
  Hack, Sebastian: Compiler Design - Syntactic and Semantic
  Analysis. Springer-Verlag Berlin Heidelberg, 2013.
