// header file for curriculum section "References"
// (c) iSAQB e.V. (https://isaqb.org)
// ===============================================

[bibliography]
== {references}

// tag::DE[]
Dieser Abschnitt enthält Quellenangaben, die ganz oder teilweise im Curriculum referenziert werden.
// end::DE[]

// tag::EN[]
This section contains references that are cited in the curriculum.
// end::EN[]

**B**

- [[[baader,Baader and Nipkow 1998]]] Baader, Franz, Nipkow, Tobias:
  Term Rewriting and All That. Cambridge University Press, 1998.

**C**

- [[[culpepper,Culpepper et al. 2019]]] Culpepper, Ryan,
  Felleisen, Matthias, Flatt, Matthew, Krishnamurthi, Shriram: From
  Macros to DSLs: The Evolution of Racket. Summit on Advances in
  Programming Languages, 2019.
  https://cs.brown.edu/~sk/Publications/Papers/Published/cffk-macros-to-dsls/

**L**

- [[[leermakers,Leermakers 1993]]] Leermakers, René: The Functional Treatment of
  Parsing. Springer Science, 1993.

**N**

- [[[nipkow,Nipkow and Klein 2014]]] Nipkow, Tobias, Klein, Gerwin:
  Concrete Semantics. Springer, 2014.

**P**

- [[[pierce,Pierce 2002]]] Pierce, Benjamin C.: Types and Programming Languages.
  MIT Press, 2002.

**V**

- [[[voelter,Völter  et al. 2014]]] Völter, Markus, Siegmun, Janet,
  Berge,  Thorsten, Kolb, Bernd: Towards user-friendly
  projectional editors. In International Conference on Software
  Language Engineering 2014. 41-61. Springer.

**W**

- [[[wilhelm,Wilhelm et al. 2021]]]  Wilhelm, Reinhard, Seidl, Helmut,
  Hack, Sebastian: Compiler Design - Syntactic and Semantic
  Analysis. Springer-Verlag Berlin Heidelberg, 2013.
